services:
  - type: web
    name: englishapp
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      cp database/database.sqlite /var/data/database.sqlite
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1